### ISSUE TITLE
Question about the license

### ISSUE THREAD

**Issue by ensisoft** [Waqar144/QSourceHighlite#2]
Hi, this looks great but the GPL license is bit of a downer. Any chance of LGPL or MIT ? If so I'd be interested to extend and contribute Lua support. Thanks

**Comment by Waqar144** [comment]
Sure, no issues.

You can send a PR changing the license even. I am okay with it. I think MIT would be a good choice.

**Comment by ensisoft** [comment]
hey, wow thanks for the extremely fast reply. 

:+1:

**Comment by Waqar144** [comment]
Out of curiosity, are you going to use it in some project or just want to contribute?

**Comment by ensisoft** [comment]
Currently prototyping different options for a (yet unreleased) game engine's built-in scripting editor.

**Comment by Waqar144** [comment]
Alright.

Just to be clear, this was written in the spirit of "highlight.js", something that is light, small, and when you don't need extra highlighting capabilities :)

**Comment by ensisoft** [comment]
> Alright.
> 
> Just to be clear, this was written in the spirit of "highlight.js", something that is light, small, and when you don't need extra highlighting capabilities :)

This looks exactly like a good fit for my needs. Couple of PRs on your way. Thanks!
