### ISSUE TITLE
Fails on Qt6

### ISSUE THREAD

**Issue by ssspeq** [Waqar144/QSourceHighlite#5]
Because QStringRef got removed from Qt6, this does not work on Qt versions > 6. See:

https://doc-snapshots.qt.io/qt6-dev/qtcore-changes-qt6.html

Any change of a fix for this? :-)

**Comment by Waqar144** [comment]
Qt6 is still pretty new, so it might take a little while to switch to that completely. and I want to keep Qt5 compatibility for at least a year or two.

So some kind of QString wrapper or using an alias will be a quick fix for now. And if that doesn't work, I will just switch to `QString` for now. The perf difference would likely not be noticeable.

Feel free to open a patch :)

**Comment by Waqar144** [comment]
Fixed with https://github.com/Waqar144/QSourceHighlite/pull/6
